#---------------> database connection parameters
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/record_db?useSSL=false&serverTimezone=UTC
    username: root
    password: Aasif@123
    driver-class-name: com.mysql.cj.jdbc.Driver


#--------->  hibernate parameters
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#-----------> Server port
server:
  port: 8181
